{% set name = "pyaaf2" %}
{% set version = "1.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 83815554dbe56aabae4cf48d02e58cd7c102733d649672832ec8a2542d3f24ad

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=2.7
  run:
    - python >=2.7

test:
  imports:
    - aaf2
    - aaf2.model
    - aaf2.model.ext

about:
  home: https://github.com/markreidvfx/pyaaf2
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A python module for reading and writing advanced authoring format files
  doc_url: https://pyaaf.readthedocs.io/en/latest

extra:
  recipe-maintainers:
    - vvzen
